[server]
host="0.0.0.0"
port="12306"

[databases.web]
name= "hoomanage"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w6o.mysql.rds.aliyuncs.com:3306"
user= "hoocustody"
password= "Eb!ZXrNt!!x5xru0"
mode= "release"

# [databases.web]
# name= "hoo"
# type= "mysql"
# url= "localhost:3306"
# user= "root"
# password= "123456"
# mode= "release"

[log]
out_file= "tmplogs/info"
err_file= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "debug"
log_path= "tmp"
log_name= "debug.log"
max_age= 24
rotation_time= 24

[email]
iam_user_name= "new-project@hoo.com"     # from地址
recipient= [ "xiaohuasheng@hoo.com" , "heimao@hoo.com" ]             # 接收地址
# recipient= [ "moyunrz@163.com" , "lananrz@163.com" ]             # 接收地址
smtp_password="BG/CV8RZPkXrtIde9ZONEO142PqfV+2lP+Fcsgq0pOMQ"
smtp_username="AKIAZXPISQLLFWOJQDQ4"

[upload]
url = "./upload" #文件存储根路径，
max_file =8 #8M