[server]
scheme = "http"
host="0.0.0.0"
port="12306"
mod="test"

# pro 生产环境
[databases.pro]
name= ""
type= "mysql"
url= ""
user= ""
password= ""
mode= "release"

# pre 准生产环境
[databases.pre]
name= ""
type= "mysql"
url= ""
user= "custody"
password= ""
mode= "release"

# test 测试环境
[databases.test]
name= ""
type= "mysql"
url= "127.0.0.1:3306"
user= ""
password= ""
mode= "release"

# local本地环境
[databases.local]
name= "custody"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "123456"
mode= "release"

[log]
out_file= "tmplogs/info"
err_file= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "debug"
log_path= "tmp"
log_name= "debug.log"
max_age= 24
rotation_time= 24

[email]
iam_user_name= ""     # from地址
recipient= [ ""]             # 接收地址
smtp_password=""
smtp_username=""
host = ""

[upload]
url = "./static" #文件存储根路径，
max_file =8 #8M