[server]
scheme = "http"
host="0.0.0.0"
port="12306"
mod="local"

# pro 生产环境
[databases.pro]
name= "hoomanage"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w6o.mysql.rds.aliyuncs.com:3306"
user= "hoocustody"
password= "Eb!ZXrNt!!x5xru0"
mode= "release"

# pre 准生产环境
[databases.pre]
name= "hoocustody_test_new"
type= "mysql"
url= "hoocustody-test-1-instance-1.cjokoae5jmn7.ap-northeast-1.rds.amazonaws.com:53306"
user= "hoocustody"
password= "Eb!ZXrNt!!x5xru0"
mode= "release"

# test 测试环境
[databases.test]
name= "root"
type= "mysql"
url= "3.115.25.173:3306"
user= "root"
password= "123456"
mode= "release"

# local本地环境
[databases.local]
name= "custody"
type= "mysql"
url= "localhost:3306"
user= "root"
password= "123456"
mode= "release"

[log]
out_file= "tmplogs/info"
err_file= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "debug"
log_path= "tmp"
log_name= "debug.log"
max_age= 24
rotation_time= 24

[email]
iam_user_name= "new-project@hoo.com"     # from地址
recipient= [ "xiaohuasheng@hoo.com" , "heimao@hoo.com" ]             # 接收地址
smtp_password="BG/CV8RZPkXrtIde9ZONEO142PqfV+2lP+Fcsgq0pOMQ"
smtp_username="AKIAZXPISQLLFWOJQDQ4"
host = "email-smtp.ap-northeast-1.amazonaws.com"

[upload]
url = "./static" #文件存储根路径，
max_file =8 #8M