[server]
scheme = "https"
host="0.0.0.0"
port="12306"
mod="test"

# pro 生产环境
[databases.pro]
name= "custody_pre"
type= "mysql"
url= "hoocustody-dev.cluster-cjokoae5jmn7.ap-northeast-1.rds.amazonaws.com:53306"
user= "custody"
password= "OpDomFBx7Wk4Lts33qg57jXh"
mode= "release"

# pre 准生产环境
[databases.pre]
name= "custody_pre"
type= "mysql"
url= "hoocustody-dev.cluster-cjokoae5jmn7.ap-northeast-1.rds.amazonaws.com:53306"
user= "custody"
password= "OpDomFBx7Wk4Lts33qg57jXh"
mode= "release"

# test 测试环境
[databases.test]
name= "custody"
type= "mysql"
url= "127.0.0.1:3306"
user= "custody"
password= "OpDomFBx7Wk4Lts33qg57jXh"
mode= "release"

# local本地环境
[databases.local]
name= "custody"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "123456"
mode= "release"

[log]
out_file= "tmplogs/info"
err_file= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "debug"
log_path= "tmp"
log_name= "debug.log"
max_age= 24
rotation_time= 24

[email]
iam_user_name= "new-project@hoo.com"     # from地址
recipient= [ "xiaohuasheng@hoo.com"]             # 接收地址
smtp_password="BGTAH2cr4Ief0SdAip2G2PwP2NH8gjQvIvqp1lANTYfk"
smtp_username="AKIA3J4EEKZXW6G5RQCZ"
host = "email-smtp.ap-northeast-1.amazonaws.com"

[upload]
url = "./static" #文件存储根路径，
max_file =8 #8M